---
name: nim_test_cyclic

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: '3 1 * * 1'

jobs:
  nim_test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        nim-version:
          - 'stable'
          - 'devel'

    steps:
      - uses: actions/checkout@v4

      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{matrix.nim-version}}

      - name: Display nim version
        run: |
          nim --version

      - name: Build and test
        run: |
          nim test
...
